version: '3.8'

services:

  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGUSER: derivzero
      PGDATABASE: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/01_init.sql:/docker-entrypoint-initdb.d/01_init.sql
      - ./postgres/02_init_views.sql:/docker-entrypoint-initdb.d/02_init_views.sql
      - ./postgres/03_seed_users.sql:/docker-entrypoint-initdb.d/03_seed_users.sql
      - ./postgres/04_set_passwords.sh:/docker-entrypoint-initdb.d/04_set_passwords.sh
    networks:
      - prem_network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - streamlit
    networks:
      - prem_network


  streamlit:
    build:
      context: .
      dockerfile: streamlit/Dockerfile
    container_name: streamlit
    restart: unless-stopped
    env_file: .env
    environment:
      DEPLOYMENT: onprem
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    volumes:
      - ./dev_env:/dev_env
    depends_on:
      - postgres
    networks:
      - prem_network

  dev_env:
    build:
      context: ./dev_env
      dockerfile: Dockerfile
    container_name: dev_env
    restart: unless-stopped
    env_file: .env
    environment:
      DEPLOYMENT: onprem
    ports:
      - "127.0.0.1:8501:8501"
    volumes:
      - ./dev_env:/dev_env
    depends_on:
      - postgres
    networks:
      - prem_network

networks:
  prem_network:
    driver: bridge

volumes:
  postgres_data:
